/*trưởng phòng*/
--1
CREATE USER xxxxxxxx98 IDENTIFIED BY xxxxxL293;
GRANT CONNECT, RESOURCE TO xxxxxxxx98;
GRANT CREATE SESSION TO xxxxxxxx98;
--2
CREATE USER xxxxxxxxx4 IDENTIFIED BY yyyyKL432;
GRANT CONNECT, RESOURCE TO xxxxxxxxx4;
GRANT CREATE SESSION TO xxxxxxxxx4;
--3
CREATE USER xxxxxxxxx6 IDENTIFIED BY zzzzzVL903;
GRANT CONNECT, RESOURCE TO xxxxxxxxx6;
GRANT CREATE SESSION TO xxxxxxxxx6;
--4
CREATE USER xxxxxxx109 IDENTIFIED BY yxzyzPQ038;
GRANT CONNECT, RESOURCE TO xxxxxxx109;
GRANT CREATE SESSION TO xxxxxxx109;
--5
CREATE USER xxxxxxxxx9 IDENTIFIED BY yxtzwMR313;
GRANT CONNECT, RESOURCE TO xxxxxxxxx9;
GRANT CREATE SESSION TO xxxxxxxxx9;
/*Giám đốc*/
--1
CREATE USER xxxxxxx102 IDENTIFIED BY Drxxz102;
GRANT CONNECT, RESOURCE TO xxxxxxx102;
GRANT CREATE SESSION TO xxxxxxx102;
--2
CREATE USER xxxxxxx104 IDENTIFIED BY Drxtz104;
GRANT CONNECT, RESOURCE TO xxxxxxx104;
GRANT CREATE SESSION TO xxxxxxx104;
--3
CREATE USER xxxxxxx106 IDENTIFIED BY Drhrlz106;
GRANT CONNECT, RESOURCE TO xxxxxxx106;
GRANT CREATE SESSION TO xxxxxxx106;
--4
CREATE USER xxxxxxx108 IDENTIFIED BY Drlxz108;
GRANT CONNECT, RESOURCE TO xxxxxxx108;
GRANT CREATE SESSION TO xxxxxxx108;
--5
CREATE USER xxxxxxx110 IDENTIFIED BY Drfkz110;
GRANT CONNECT, RESOURCE TO xxxxxxx110;
GRANT CREATE SESSION TO xxxxxxx110;
/*trưởng chi nhánh*/
CREATE USER xxxxxxxxx9 IDENTIFIED BY xxxxxxxxx9;
GRANT CONNECT, RESOURCE TO xxxxxxxxx9;
GRANT CREATE SESSION TO xxxxxxxxx9;
