--USER - trưởng phòng
--1
CREATE USER xxxxxxxx98 IDENTIFIED BY xxxxxL293;
GRANT CONNECT, RESOURCE TO xxxxxxxx98;
GRANT UNLIMITED TABLESPACE TO xxxxxxxx98;
GRANT SELECT, INSERT, UPDATE, ALTER  TO xxxxxxxx98;
--2
CREATE USER xxxxxxxxx4 IDENTIFIED BY yyyyKL432;
GRANT CONNECT, RESOURCE TO xxxxxxxxx4;
GRANT UNLIMITED TABLESPACE TO xxxxxxxxx4;
GRANT SELECT, INSERT, UPDATE, ALTER  TO xxxxxxxxx4;
--3
CREATE USER xxxxxxxxx6 IDENTIFIED BY zzzzzVL903;
GRANT CONNECT, RESOURCE TO xxxxxxxxx6;
GRANT UNLIMITED TABLESPACE TO xxxxxxxxx6;
GRANT SELECT, INSERT, UPDATE, ALTER  TO xxxxxxxxx6;
--4
CREATE USER xxxxxxx109 IDENTIFIED BY yxzyzPQ038;
GRANT CONNECT, RESOURCE TO xxxxxxx109;
GRANT UNLIMITED TABLESPACE TO xxxxxxx109;
GRANT SELECT, INSERT, UPDATE, ALTER  TO xxxxxxx109;
--5
CREATE USER xxxxxxxxx9 IDENTIFIED BY yxtzwMR313;
GRANT CONNECT, RESOURCE TO xxxxxxxxx9;
GRANT UNLIMITED TABLESPACE TO xxxxxxxxx9;
GRANT SELECT, INSERT, UPDATE, ALTER  TO xxxxxxxxx9;
--ROLE - trưởng phòng
CREATE ROLE depart_chief IDENTIFIED BY DhcLV404;
GRANT SELECT, UPDATE ON Project;
GRANT depart_chief TO xxxxxxxx98, xxxxxxxxx4, xxxxxxxxx6, xxxxxxx109, xxxxxxxxx9;

